// <auto-generated />
namespace NUMLPay_Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class FeeInstallmentsandUnpaidFeesTableUpdatedSTATUS : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FeeInstallmentsandUnpaidFeesTableUpdatedSTATUS));
        
        string IMigrationMetadata.Id
        {
            get { return "202308070858089_Fee Installments and Unpaid Fees Table Updated (STATUS)"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
