// <auto-generated />
namespace NUMLPay_Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class UsersandAdminTablechangedAcademicTabledeletedmadsomechnages : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UsersandAdminTablechangedAcademicTabledeletedmadsomechnages));
        
        string IMigrationMetadata.Id
        {
            get { return "202307191240501_Users and Admin Table changed, Academic Table deleted mad some chnages."; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
