// <auto-generated />
namespace NUMLPay_Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Feestructurevtableupdated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Feestructurevtableupdated));
        
        string IMigrationMetadata.Id
        {
            get { return "202308051316247_Fee structurev table updated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
