// <auto-generated />
namespace NUMLPay_Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class UnpaidFeesTableUpdatedSecutirycolumnadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UnpaidFeesTableUpdatedSecutirycolumnadded));
        
        string IMigrationMetadata.Id
        {
            get { return "202308131513501_Unpaid Fees Table Updated Secutiry column added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
