// <auto-generated />
namespace NUMLPay_Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class InstallmentMangementfee_foradded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InstallmentMangementfee_foradded));
        
        string IMigrationMetadata.Id
        {
            get { return "202402271808362_Installment Mangement fee_for added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
