// <auto-generated />
namespace NUMLPay_Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class FeeInstallmentsTABLEupdatednoInstammnetManagemunetID : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FeeInstallmentsTABLEupdatednoInstammnetManagemunetID));
        
        string IMigrationMetadata.Id
        {
            get { return "202308061202465_FeeInstallments TABLE updated no InstammnetManagemunet ID"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
