// <auto-generated />
namespace NUMLPay_Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class shifttableis_activeadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(shifttableis_activeadded));
        
        string IMigrationMetadata.Id
        {
            get { return "202307281132518_shift table is_active added."; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
