// <auto-generated />
namespace NUMLPay_Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class DbupdatedSummerEnrollmentis_activedeleted : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DbupdatedSummerEnrollmentis_activedeleted));
        
        string IMigrationMetadata.Id
        {
            get { return "202401311730413_Db updated. Summer Enrollment is_active deleted."; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
