// <auto-generated />
namespace NUMLPay_Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class DbupdatedSummerFeeSessionYearAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DbupdatedSummerFeeSessionYearAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "202401301436100_Db updated. Summer Fee Session Year Added."; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
